### ISSUE TITLE
Filling fields with type 'Text filled with autocomplete' does not work

### ISSUE THREAD

**Issue by OlaTrznadel** [dataconsulting-pl/APEX-Low-Test-Framework#28]
Overall functionality works correctly for field with type 'text'. Error occurs when field type is 'text filled with autocomplete' and class="oj-inputsearch-input apex-item-text apex-item-auto-complete inputsearch"

Step to reproduce:
 Scenario: Enter text into text fields
    Given user navigates to 'Customers' page
    And user clicked on the 'Add Customer' button
    When user enters text into text fields according to data in table:
    |Supplier name | TCV | ARR |
    | Hermes | AB1 | 23a |
    Then verify, that value of text item 'Customer Name' is 'Customer 1'
    And verify, that value of text item 'TCV' is 'AB1'
    And verify, that value of text item 'ARR' is '23a'

Step failed
org.openqa.selenium.InvalidElementStateException: invalid element state
  (Session info: chrome=108.0.5359.126)
Build info: version: '4.7.2', revision: '4d4020c3b7'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '19.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [692c945d61f7035b355aa8f775af7229, clearElement {id=0d9c30a8-d562-484a-9bef-3c2007b8d367}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 108.0.5359.126, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: C:\Users\user\AppData\Local...}, goog:chromeOptions: {debuggerAddress: localhost:56808}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:56808/devtoo..., se:cdpVersion: 108.0.5359.126, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on WINDOWS (692c945d61f7035b355aa8f775af7229)] -> id: 111_Supplier_name_field]
Session ID: 692c945d61f7035b355aa8f775af7229
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:535)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:257)
	at org.openqa.selenium.remote.RemoteWebElement.clear(RemoteWebElement.java:132)
	at pl.dataconsulting.APEX_TAF.APEXComponents.BaseComponent.sendKeys(BaseComponent.java:141)
	at pl.dataconsulting.APEX_TAF.APEXComponents.TextComponent.enterStringIntoTextItem(TextComponent.java:31)
	at pl.dataconsulting.APEX_TAF.stepDefinitions.TextFieldSteps.user_enters_text_into_field(TextFieldSteps.java:41)
	at ✽.user enters 'Hermes in 'Supplier name' field(file:///C:/Users/user/IdeaProjects/APEX-Low-Test-Framework/src/test/java/xxx/exclamation_mark_validation.feature:26)

**Comment by borowskikrz** [comment]
Corrected in develop branch.
