### ISSUE TITLE
Validation message does not work for shuttle field

### ISSUE THREAD

**Issue by OlaTrznadel** [dataconsulting-pl/APEX-Low-Test-Framework#29]
Functionality does not work for fields with type 'Shuttle'.

Step failed
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(@class,'t-Form-label') and starts-with(text(),'111_name_field')]/."}
  (Session info: chrome=108.0.5359.126)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.7.2', revision: '4d4020c3b7'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '19.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [7bf7a6512758c1390c4d0f385553eb0a, findElement {using=xpath, value=//*[contains(@class,'t-Form-label') and starts-with(text(),'P3020_WH_LIST_NEW')]/.}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 108.0.5359.126, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: C:\Users\user\AppData\Local...}, goog:chromeOptions: {debuggerAddress: localhost:60049}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:60049/devtoo..., se:cdpVersion: 108.0.5359.126, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 7bf7a6512758c1390c4d0f385553eb0a
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:535)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:351)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:343)
	at pl.dataconsulting.APEX_TAF.APEXComponents.BaseComponent.getValidationWebElementByLabel(BaseComponent.java:222)
	at pl.dataconsulting.APEX_TAF.APEXComponents.TextComponent.verifyValidationMessage(TextComponent.java:88)
	at pl.dataconsulting.APEX_TAF.stepDefinitions.ValidationItemSteps.verify_validation_message(ValidationItemSteps.java:30)
	at ✽.validation message 'Validation text' for '111_name_field' field is displayed(file:///C:/Users/user/IdeaProjects/APEX-Low-Test-Framework/src/test/java/xxx/xxx_exclamation_mark_validation.feature:87)

**Comment by borowskikrz** [comment]
Validation steps work also for shuttle items. In that case, there were two items with the same name visible on the page.
The error message should be corrected, so that is more user freindly.

**Comment by borowskikrz** [comment]
It is possible now to find also the validation messages by id of the filed. In case one or more fields are found, please try to search by id not name. 
The steps to distinguish fields with the same name will be implemented in feature.
